@echo off
cls
set framework=echo using the o++ FrameWork
set end=exit
set stop=pause
set delay=setlocal EnableDelayedExpansion
set loop=goto 0
set run=start
set int=set
set getimput=set /p
set return=goto
set print=echo
set import=call
set clear=cls
set col=color
set namespace=title
set function=set
set listtask=tasklist
set if=if
set remove=del
set class=set class
set changedir=chdir
set prevdir=cd\
set copy=copy
set rename=rename
set olist=echo edit the bat file to see all of the commands or watch a tutorial this programeing launge is only made for eazyer condeing like "python"
set link=start
set killtask=taskkill /f /im
set plus=set /a
set readscrip=chdir scripts
set folder=md
set substr=:~d,n
set substred=:~d
set log=type